[package]
name = "takara"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["ws"] }
futures-util = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
